export interface SchoolOption {
  value: string;
  label: string;
}

export const SCHOOL_OPTIONS: SchoolOption[] = [
  { value: "BOUESTI - Ikere-Ekiti", label: "BOUESTI - Ikere-Ekiti" },
  { value: "Abia State University", label: "Abia State University" },
  { value: "Abubakar Tafawa Balewa University", label: "Abubakar Tafawa Balewa University" },
  { value: "Achievers University, Owo", label: "Achievers University, Owo" },
  { value: "Adamawa State University", label: "Adamawa State University" },
  { value: "Adekunle Ajasin University", label: "Adekunle Ajasin University" },
  { value: "Adeleke University", label: "Adeleke University" },
  { value: "Admiralty University of Nigeria", label: "Admiralty University of Nigeria" },
  { value: "Afe Babalola University", label: "Afe Babalola University" },
  { value: "African University of Science and Technology", label: "African University of Science and Technology" },
  { value: "Ahmadu Bello University", label: "Ahmadu Bello University" },
  { value: "Ajayi Crowther University", label: "Ajayi Crowther University" },
  { value: "Akwa Ibom State University", label: "Akwa Ibom State University" },
  { value: "Al-Hikmah University", label: "Al-Hikmah University" },
  { value: "Al-Qalam University, Katsina", label: "Al-Qalam University, Katsina" },
  { value: "Alex Ekwueme Federal University, Ndufu-Alike", label: "Alex Ekwueme Federal University, Ndufu-Alike" },
  { value: "Ambrose Alli University", label: "Ambrose Alli University" },
  { value: "American University of Nigeria", label: "American University of Nigeria" },
  { value: "Anchor University, Lagos", label: "Anchor University, Lagos" },
  { value: "Arthur Jarvis University", label: "Arthur Jarvis University" },
  { value: "Atiba University", label: "Atiba University" },
  { value: "Augustine University", label: "Augustine University" },
  { value: "Babcock University", label: "Babcock University" },
  { value: "Bauchi State University", label: "Bauchi State University" },
  { value: "Bayelsa Medical University", label: "Bayelsa Medical University" },
  { value: "Bayero University Kano", label: "Bayero University Kano" },
  { value: "Baze University", label: "Baze University" },
  { value: "Bells University of Technology", label: "Bells University of Technology" },
  { value: "Benue State University", label: "Benue State University" },
  { value: "Bingham University", label: "Bingham University" },
  { value: "Bornu State University", label: "Bornu State University" },
  { value: "Caleb University", label: "Caleb University" },
  { value: "Caritas University", label: "Caritas University" },
  { value: "Chrisland University", label: "Chrisland University" },
  { value: "Christopher University", label: "Christopher University" },
  { value: "Clifford University", label: "Clifford University" },
  { value: "Coal City University", label: "Coal City University" },
  { value: "Covenant University", label: "Covenant University" },
  { value: "Crawford University", label: "Crawford University" },
  { value: "Crescent University", label: "Crescent University" },
  { value: "Delta State University, Abraka", label: "Delta State University, Abraka" },
  { value: "Dominican University", label: "Dominican University" },
  { value: "Eastern Palm University", label: "Eastern Palm University" },
  { value: "Ebonyi State University", label: "Ebonyi State University" },
  { value: "Edo University Iyamho", label: "Edo University Iyamho" },
  { value: "Ekiti State University", label: "Ekiti State University" },
  { value: "Elizade University", label: "Elizade University" },
  { value: "Enugu State University of Science and Technology", label: "Enugu State University of Science and Technology" },
  { value: "Evangel University", label: "Evangel University" },
  { value: "Federal University Gashua", label: "Federal University Gashua" },
  { value: "Federal University of Petroleum Resources, Effurun", label: "Federal University of Petroleum Resources, Effurun" },
  { value: "Federal University of Technology, Akure", label: "Federal University of Technology, Akure" },
  { value: "Federal University of Technology, Minna", label: "Federal University of Technology, Minna" },
  { value: "Federal University of Technology, Owerri", label: "Federal University of Technology, Owerri" },
  { value: "Federal University Otuoke", label: "Federal University Otuoke" },
  { value: "Federal University Wukari", label: "Federal University Wukari" },
  { value: "Federal University, Dutse", label: "Federal University, Dutse" },
  { value: "Federal University, Dutsin-Ma", label: "Federal University, Dutsin-Ma" },
  { value: "Federal University, Gusau", label: "Federal University, Gusau" },
  { value: "Federal University, Kashere", label: "Federal University, Kashere" },
  { value: "Federal University, Lafia", label: "Federal University, Lafia" },
  { value: "Federal University, Lokoja", label: "Federal University, Lokoja" },
  { value: "Federal University, Ndifu-Alike", label: "Federal University, Ndifu-Alike" },
  { value: "Federal University, Oye-Ekiti", label: "Federal University, Oye-Ekiti" },
  { value: "Godfrey Okoye University", label: "Godfrey Okoye University" },
  { value: "Gombe State University", label: "Gombe State University" },
  { value: "Gregory University", label: "Gregory University" },
  { value: "Hallmark University", label: "Hallmark University" },
  { value: "Hezekiah University", label: "Hezekiah University" },
  { value: "Ibrahim Badamasi Babangida University", label: "Ibrahim Badamasi Babangida University" },
  { value: "Ignatius Ajuru University of Education", label: "Ignatius Ajuru University of Education" },
  { value: "Imo State University", label: "Imo State University" },
  { value: "Joseph Ayo Babalola University", label: "Joseph Ayo Babalola University" },
  { value: "Kaduna State University", label: "Kaduna State University" },
  { value: "Kano University of Science and Technology", label: "Kano University of Science and Technology" },
  { value: "Kebbi State University of Science and Technology", label: "Kebbi State University of Science and Technology" },
  { value: "Kings University", label: "Kings University" },
  { value: "Kogi State University", label: "Kogi State University" },
  { value: "Kola Daisi University", label: "Kola Daisi University" },
  { value: "Kwara State University", label: "Kwara State University" },
  { value: "Landmark University", label: "Landmark University" },
  { value: "Lead City University", label: "Lead City University" },
  { value: "Madonna University", label: "Madonna University" },
  { value: "McPherson University", label: "McPherson University" },
  { value: "Michael and Cecilia Ibru University", label: "Michael and Cecilia Ibru University" },
  { value: "Modibbo Adama University", label: "Modibbo Adama University" },
  { value: "Mountain Top University", label: "Mountain Top University" },
  { value: "Nasarawa State University", label: "Nasarawa State University" },
  { value: "National Open University of Nigeria", label: "National Open University of Nigeria" },
  { value: "Niger Delta University", label: "Niger Delta University" },
  { value: "Nigerian Defence Academy", label: "Nigerian Defence Academy" },
  { value: "Nigerian Maritime University", label: "Nigerian Maritime University" },
  { value: "Nile University of Nigeria", label: "Nile University of Nigeria" },
  { value: "Nnamdi Azikiwe University", label: "Nnamdi Azikiwe University" },
  { value: "Novena University", label: "Novena University" },
  { value: "Obafemi Awolowo University", label: "Obafemi Awolowo University" },
  { value: "Obong University", label: "Obong University" },
  { value: "Oduduwa University", label: "Oduduwa University" },
  { value: "Olabisi Onabanjo University", label: "Olabisi Onabanjo University" },
  { value: "Ondo State University of Science and Technology", label: "Ondo State University of Science and Technology" },
  { value: "Osun State University", label: "Osun State University" },
  { value: "Pan-Atlantic University", label: "Pan-Atlantic University" },
  { value: "Paul University", label: "Paul University" },
  { value: "Plateau State University", label: "Plateau State University" },
  { value: "Redeemer's University", label: "Redeemer's University" },
  { value: "Renaissance University", label: "Renaissance University" },
  { value: "Ritman University", label: "Ritman University" },
  { value: "Rivers State University", label: "Rivers State University" },
  { value: "Salem University", label: "Salem University" },
  { value: "Samuel Adegboyega University", label: "Samuel Adegboyega University" },
  { value: "Skyline University Nigeria", label: "Skyline University Nigeria" },
  { value: "Sokoto State University", label: "Sokoto State University" },
  { value: "Southwestern University", label: "Southwestern University" },
  { value: "Spiritan University", label: "Spiritan University" },
  { value: "Summit University", label: "Summit University" },
  { value: "Tai Solarin University of Education", label: "Tai Solarin University of Education" },
  { value: "Tansian University", label: "Tansian University" },
  { value: "Taraba State University", label: "Taraba State University" },
  { value: "Thomas Adewumi University", label: "Thomas Adewumi University" },
  { value: "University of Abuja", label: "University of Abuja" },
  { value: "University of Agriculture, Abeokuta", label: "University of Agriculture, Abeokuta" },
  { value: "University of Agriculture, Makurdi", label: "University of Agriculture, Makurdi" },
  { value: "University of Benin", label: "University of Benin" },
  { value: "University of Calabar", label: "University of Calabar" },
  { value: "University of Ibadan", label: "University of Ibadan" },
  { value: "University of Ilorin", label: "University of Ilorin" },
  { value: "University of Jos", label: "University of Jos" },
  { value: "University of Lagos", label: "University of Lagos" },
  { value: "University of Maiduguri", label: "University of Maiduguri" },
  { value: "University of Medical Sciences, Ondo", label: "University of Medical Sciences, Ondo" },
  { value: "University of Nigeria, Nsukka", label: "University of Nigeria, Nsukka" },
  { value: "University of Port Harcourt", label: "University of Port Harcourt" },
  { value: "University of Uyo", label: "University of Uyo" },
  { value: "Usmanu Danfodiyo University", label: "Usmanu Danfodiyo University" },
  { value: "Veritas University", label: "Veritas University" },
  { value: "Wellspring University", label: "Wellspring University" },
  { value: "Wesley University", label: "Wesley University" },
  { value: "Western Delta University", label: "Western Delta University" },
  { value: "Yobe State University", label: "Yobe State University" },
];

export const SCHOOL_LOCATION_KEYWORDS: Record<string, string[]> = {
  "BOUESTI - Ikere-Ekiti": ["Ikere", "Uro", "Odo Oja", "Afao", "Olumilua", "Ajebandele", "Ikoyi Estate", "Amoye", "Oke 'Kere"],
  "Ahmadu Bello University": ["Zaria", "Samaru", "Kongo", "Tudun Wada"],
  "University of Lagos": ["Akoka", "Yaba", "Bariga", "Surulere", "Gbagada"],
  "Obafemi Awolowo University": ["Ile-Ife", "Modakeke", "Lagere"],
  "University of Ibadan": ["Ibadan", "Bodija", "Agbowo", "Sango", "Abadina"],
  "University of Benin": ["Benin", "Ugbowo", "Ekosodin", "Uselu"],
  "Federal University of Technology, Akure": ["Akure", "Oba-Ile", "Aule", "Ijapo"],
  "University of Ilorin": ["Ilorin", "Tanke", "Oke-Odo", "Fate", "Gaa-Akanbi"],
  "University of Nigeria, Nsukka": ["Nsukka", "Odenigwe", "Ugwuoye"],
  "Covenant University": ["Ota", "Canaanland", "Iyana-Iyesi", "Sango-Ota"],
  "Bayero University Kano": ["Kano", "Gwale", "Tudun Wada", "Nasarawa", "BUK Road"],
  "Nnamdi Azikiwe University": ["Awka", "Ifite", "Amawbia", "Unizik"],
  "University of Port Harcourt": ["Port Harcourt", "Choba", "Rumuola", "Rumuokoro"],
  "University of Calabar": ["Calabar", "Ekorinim", "Satellite Town"],
  "University of Abuja": ["Abuja", "Gwagwalada", "Pyakassa"],
  "Babcock University": ["Ilishan-Remo", "Ilishan", "Sagamu"],
  "Landmark University": ["Omu-Aran", "Omu Aran"],
  "Benue State University": ["Makurdi", "Gboko Road", "North Bank"],
  "Ekiti State University": ["Ado-Ekiti", "Ado", "Basiri"],
  "Adekunle Ajasin University": ["Akungba", "Akungba-Akoko", "Akoko"],
  "Rivers State University": ["Port Harcourt", "Nkpolu", "Rumuola"],
  "Osun State University": ["Osogbo", "Ifetedo", "Ejigbo"],
  "Kwara State University": ["Malete", "Ilorin"],
  "Federal University of Technology, Minna": ["Minna", "Bosso", "Chanchaga"],
  "Federal University of Technology, Owerri": ["Owerri", "Ihiagwa", "Nekede"],
  "University of Maiduguri": ["Maiduguri", "Old Maiduguri Road", "Gamboru"],
  "University of Jos": ["Jos", "Bauchi Road", "Zaria Road", "Anglo-Jos"],
  "University of Uyo": ["Uyo", "Nwaniba Road", "Itu Road"],
  "Nasarawa State University": ["Keffi", "Nasarawa"],
  "Gombe State University": ["Gombe", "Tudun Wada"],
  "Usmanu Danfodiyo University": ["Sokoto", "Mabera", "Gawon Nama"],
  "Plateau State University": ["Bokkos", "Jos", "Vom"],
  "Kogi State University": ["Anyigba", "Ankpa"],
  "Olabisi Onabanjo University": ["Ago-Iwoye", "Ijebu-Ode"],
  "Redeemer's University": ["Ede", "Redemption City"],
  "Lead City University": ["Ibadan", "Toll Gate", "Elebu"],
  "American University of Nigeria": ["Yola", "Jimeta"],
  "Baze University": ["Abuja", "Jabi", "Kado"],
  "Nile University of Nigeria": ["Abuja", "Jabi", "Idu"],
  "Afe Babalola University": ["Ado-Ekiti", "Afe Babalola Way"],
  "Elizade University": ["Ilara-Mokin", "Ilara", "Akure"],
  "Niger Delta University": ["Wilberforce Island", "Amassoma", "Yenagoa"],
  "Delta State University, Abraka": ["Abraka", "Asaba", "Warri"],
  "Ambrose Alli University": ["Ekpoma", "Uromi", "Irrua"],
};
